resource "aws_iam_policy" "external_dns" {
  name        = "${var.cluster_name}-external-dns"
  description = "Allow external-dns to manage Route 53 records in the ${var.domain} hosted zone"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = "route53:ChangeResourceRecordSets"
        Resource = "arn:aws:route53:::hostedzone/${data.aws_route53_zone.main.zone_id}"
      },
      {
        Effect = "Allow"
        Action = [
          "route53:ListHostedZones",
          "route53:ListResourceRecordSets",
          "route53:ListTagsForResource",
        ]
        Resource = "*"
      },
    ]
  })
}

resource "aws_iam_role" "external_dns" {
  name               = "${var.cluster_name}-external-dns"
  assume_role_policy = data.aws_iam_policy_document.pod_identity_trust.json
}

resource "aws_iam_role_policy_attachment" "external_dns" {
  role       = aws_iam_role.external_dns.name
  policy_arn = aws_iam_policy.external_dns.arn
}

resource "aws_eks_pod_identity_association" "external_dns" {
  cluster_name    = module.eks.cluster_name
  namespace       = "external-dns"
  service_account = "external-dns"
  role_arn        = aws_iam_role.external_dns.arn
}

resource "kubernetes_namespace" "external_dns" {
  metadata {
    name = "external-dns"
  }
}

resource "helm_release" "external_dns" {
  name       = "external-dns"
  namespace  = kubernetes_namespace.external_dns.metadata[0].name
  repository = "https://kubernetes-sigs.github.io/external-dns"
  chart      = "external-dns"
  version    = "1.15.0"

  values = [
    yamlencode({
      provider = {
        name = "aws"
      }
      env = [
        {
          name  = "AWS_REGION"
          value = var.region
        },
      ]
      serviceAccount = {
        create = true
        name   = "external-dns"
        # No annotations needed: Pod Identity binds the SA to the role.
      }
      domainFilters = [var.domain]
      policy        = "upsert-only"
      txtOwnerId    = var.cluster_name
      # Post-Phase 12 of Gateway API migration: 'ingress' source dropped
      # since all 10 Ingresses have been deleted. Only 'service' (for
      # LoadBalancer Service DNS) and 'gateway-httproute' (for HTTPRoute
      # hostnames) remain. RBAC for httproutes was auto-generated by
      # the chart when this source was added in Phase 0.
      sources = [
        "service",
        "gateway-httproute",
      ]
      registry = "txt"
      logLevel = "info"
      interval = "1m"
    })
  ]

  depends_on = [
    module.eks,
    aws_eks_pod_identity_association.external_dns,
    helm_release.alb_controller,
  ]
}
