# Phase #42: oauth2-proxy in front of the Argo Rollouts dashboard.
#
# Closes the Phase #38 documented security gap: the dashboard had no
# native auth, so anyone with the URL could read all Rollout state.
# oauth2-proxy intercepts unauthenticated browser requests, redirects
# to Keycloak for sign-in, and forwards authenticated requests to
# the dashboard upstream.
#
# Wiring shape (post-this-commit):
#
#   Browser                    Istio Gateway          oauth2-proxy            argo-rollouts-dashboard
#   --------    --(443)-->     --(HTTPRoute)-->       --(upstream)-->         --(3100)-->
#                                                       (cookie auth, OIDC)
#
# The HTTPRoute backendRef in argo-rollouts.tf is updated to point at
# the oauth2-proxy Service instead of the dashboard Service. Auth-
# enticated requests flow through oauth2-proxy to the dashboard with
# user identity populated in X-Forwarded-User / X-Forwarded-Email
# headers (the dashboard ignores these but the audit trail shows up
# in Istio access logs).
#
# Keycloak client config:
#   client_id: rollouts-dashboard (CONFIDENTIAL, secret-protected)
#   redirect URI: https://rollouts.${var.domain}/oauth2/callback
#                  (oauth2-proxy default callback path)
#   web origin: https://rollouts.${var.domain}
#   auth flow: standard (Authorization Code) only — no direct/SA grants
#
# Cookie secret: 32-byte random base64. Generated by Terraform's
# random_bytes resource and stored in a K8s Secret in the
# argo-rollouts ns. Rotation: tainting the random_bytes resource
# generates a new value on next apply, which invalidates all
# existing user sessions (forces re-auth). Acceptable lab behavior.
#
# Same Keycloak realm as Grafana / ArgoCD / Langgraph / chat-ui, so
# users get SSO-style session reuse — sign in once across grafana.,
# argocd., chat., and now rollouts.${var.domain}. Logout is
# per-app today; a future phase could wire up the Keycloak
# back-channel logout endpoint to invalidate all sessions at once.

resource "keycloak_openid_client" "rollouts_dashboard" {
  realm_id    = var.cluster_name
  client_id   = "rollouts-dashboard"
  name        = "Argo Rollouts Dashboard"
  enabled     = true
  access_type = "CONFIDENTIAL"

  standard_flow_enabled        = true
  direct_access_grants_enabled = false
  service_accounts_enabled     = false

  root_url = "https://rollouts.${var.domain}"
  base_url = "https://rollouts.${var.domain}"

  valid_redirect_uris = [
    # oauth2-proxy's default callback path. Must match what
    # oauth2-proxy is configured to use (--redirect-url below).
    "https://rollouts.${var.domain}/oauth2/callback",
  ]

  web_origins = [
    "https://rollouts.${var.domain}",
  ]
}

# Random cookie secret for oauth2-proxy session encryption. 32 bytes
# is the size oauth2-proxy expects for its --cookie-secret flag when
# using AES-CFB (which it does by default for non-OIDC providers).
# Length matters: providing fewer bytes triggers a startup error.
resource "random_bytes" "oauth2_proxy_cookie_secret" {
  length = 32
}

resource "kubernetes_secret" "oauth2_proxy" {
  metadata {
    # Name deliberately NOT "oauth2-proxy" — that conflicts with
    # the helm chart's auto-created Secret (named after the release).
    # Use a -creds suffix so the chart can manage its own Secret
    # and we can hold the Keycloak/cookie secrets in a separate one
    # that the chart references via config.existingSecret.
    name      = "oauth2-proxy-creds"
    namespace = kubernetes_namespace.argo_rollouts.metadata[0].name
  }
  type = "Opaque"
  data = {
    # Key names match what oauth2-proxy/manifests chart 7.x expects
    # when reading from existingSecret: client-id, client-secret,
    # cookie-secret. Renaming any of these breaks the chart's env
    # mapping and oauth2-proxy starts up with empty credentials.
    client-id     = keycloak_openid_client.rollouts_dashboard.client_id
    client-secret = keycloak_openid_client.rollouts_dashboard.client_secret
    cookie-secret = random_bytes.oauth2_proxy_cookie_secret.base64
  }
}

resource "helm_release" "oauth2_proxy" {
  name       = "oauth2-proxy"
  namespace  = kubernetes_namespace.argo_rollouts.metadata[0].name
  repository = "https://oauth2-proxy.github.io/manifests"
  chart      = "oauth2-proxy"
  # Chart version pinned for reproducibility. Bump cadence: check
  # https://github.com/oauth2-proxy/manifests/releases for tags.
  version = "7.7.4"

  values = [
    yamlencode({
      # Chart values key path is `config.*` (NOT `configuration.*` —
      # that was a wrong guess on first attempt; using the wrong key
      # silently accepts the values as ad-hoc fields and falls back
      # to chart defaults, which means existingSecret was never set
      # and the chart tried to create its own "oauth2-proxy" Secret
      # that collided with the kubernetes_secret resource above).
      config = {
        # Reference the separate -creds Secret rather than inlining
        # secrets in helm values (which would land in the release
        # state in plaintext-readable form).
        existingSecret = kubernetes_secret.oauth2_proxy.metadata[0].name
        # The full oauth2-proxy config file body. The chart writes
        # this into a ConfigMap and starts oauth2-proxy with
        # --config=/etc/oauth2_proxy/oauth2_proxy.cfg.
        configFile = <<-EOT
          provider = "oidc"
          oidc_issuer_url = "https://keycloak.${var.domain}/realms/${var.cluster_name}"
          redirect_url = "https://rollouts.${var.domain}/oauth2/callback"
          upstreams = ["http://argo-rollouts-dashboard.argo-rollouts.svc.cluster.local:3100"]
          email_domains = ["*"]
          cookie_secure = true
          cookie_httponly = true
          cookie_samesite = "lax"
          # Skip the "Sign in with OIDC" button — go straight to
          # Keycloak. One less click for operators.
          skip_provider_button = true
          # Pass downstream apps the user identity headers so
          # access logs can attribute requests. Dashboard itself
          # ignores them.
          pass_user_headers = true
          set_xauthrequest = true
          # Bypass the auth check for /metrics and /ping endpoints
          # so kube-prometheus-stack and kubelet probes don't get
          # 302'd to Keycloak.
          skip_auth_routes = ["/ping", "/metrics"]
          # Listen on all addresses for the K8s Service to reach.
          http_address = "0.0.0.0:4180"
          metrics_address = "0.0.0.0:44180"
        EOT
      }

      service = {
        type       = "ClusterIP"
        portNumber = 80
      }

      # No ingress on the chart — the existing HTTPRoute (managed
      # in argo-rollouts.tf) is the entrypoint, just pointed at the
      # oauth2-proxy Service now.
      ingress = {
        enabled = false
      }

      # Single replica is fine for the lab. oauth2-proxy is
      # stateless except for the encrypted cookie, so multi-replica
      # works without sticky sessions, but the lab's traffic
      # doesn't justify HA.
      replicaCount = 1

      resources = {
        requests = {
          cpu    = "10m"
          memory = "32Mi"
        }
        limits = {
          cpu    = "200m"
          memory = "128Mi"
        }
      }

      # ServiceMonitor for kube-prometheus-stack to scrape oauth2-
      # proxy's own /metrics — request latency, auth success/failure
      # rates. Useful signal for "is the auth layer healthy?"
      metrics = {
        enabled = true
        servicemonitor = {
          enabled = true
          labels = {
            release = "kube-prometheus-stack"
          }
        }
      }
    })
  ]

  depends_on = [
    helm_release.argo_rollouts,
    kubernetes_secret.oauth2_proxy,
    keycloak_openid_client.rollouts_dashboard,
  ]
}
