# Vault declarative config (policies, auth roles, seed secrets).
#
# Bring-up order on a fresh cluster:
#   1. terraform apply -target=helm_release.vault \
#                       -target=aws_eks_pod_identity_association.vault
#   2. kubectl -n vault exec -it vault-0 -- vault operator init \
#        -recovery-shares=5 -recovery-threshold=3
#      -> save root + recovery keys to 1Password
#   3. ./vault-approle-bootstrap.sh  (uses root token to create the AppRole
#      for terraform; prints role_id + secret_id)
#   4. export TF_VAR_vault_terraform_role_id=...
#      export TF_VAR_vault_terraform_secret_id=...
#   5. terraform apply  (applies this file + everything else)

# =============================================================================
# Pilot: rag-service consumes a demo secret via Vault Agent Injector sidecar
# =============================================================================

resource "vault_policy" "rag_service" {
  name = "rag-service"

  policy = <<-EOT
    # Read-only on secrets under secret/rag-service/*
    path "secret/data/rag-service/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/rag-service/*" {
      capabilities = ["read", "list"]
    }
  EOT
}

resource "vault_kubernetes_auth_backend_role" "rag_service" {
  backend                          = "kubernetes"
  role_name                        = "rag-service"
  bound_service_account_names      = ["rag-service"]
  bound_service_account_namespaces = ["rag"]
  token_ttl                        = 3600
  token_max_ttl                    = 86400
  token_policies                   = [vault_policy.rag_service.name]
}

# Demo secret so we can prove sidecar injection works end-to-end. Gets
# rendered into /vault/secrets/demo inside the rag-service container when
# the pod is annotated with the vault.hashicorp.com/agent-inject-* keys.
resource "vault_kv_secret_v2" "rag_service_demo" {
  mount = "secret"
  name  = "rag-service/demo"

  data_json = jsonencode({
    hello         = "from vault"
    rotation_note = "this value comes from Vault via agent injector sidecar"
  })
}

# =============================================================================
# Grafana: admin password + Keycloak OIDC client secret via sidecar injection
# =============================================================================
# SA is created by the kube-prometheus-stack grafana subchart, named
# <release>-grafana = kube-prometheus-stack-grafana.

resource "vault_policy" "grafana" {
  name = "grafana"

  policy = <<-EOT
    path "secret/data/grafana/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/grafana/*" {
      capabilities = ["read", "list"]
    }
  EOT
}

resource "vault_kubernetes_auth_backend_role" "grafana" {
  backend                          = "kubernetes"
  role_name                        = "grafana"
  bound_service_account_names      = ["kube-prometheus-stack-grafana"]
  bound_service_account_namespaces = ["monitoring"]
  token_ttl                        = 3600
  token_max_ttl                    = 86400
  token_policies                   = [vault_policy.grafana.name]
}

# Grafana admin password sourced from tfvars; Vault is the runtime delivery
# path. Rotating in tfvars + applying re-writes Vault, and the next pod
# restart picks it up via the sidecar (but note: admin password lives in
# Grafana's SQLite after first boot, so rotation needs a UI/API change too).
resource "vault_kv_secret_v2" "grafana_admin" {
  mount = "secret"
  name  = "grafana/admin"

  data_json = jsonencode({
    password = var.grafana_admin_password
  })
}

# Keycloak OIDC client secret for Grafana, generated by random_password in
# keycloak-realm.tf and also baked into the realm JSON (Keycloak's side of
# the pair). Here we deliver it to Grafana via sidecar instead of a k8s
# Secret + envValueFrom.
resource "vault_kv_secret_v2" "grafana_oidc" {
  mount = "secret"
  name  = "grafana/oidc"

  data_json = jsonencode({
    client_secret = random_password.keycloak_grafana_client_secret.result
  })
}

# =============================================================================
# ArgoCD: Keycloak OIDC client secret via Vault Secrets Operator (VSO)
# =============================================================================
# ArgoCD's oidc.config requires a k8s Secret (no file/env fallback), so VSO
# syncs this Vault path into a k8s Secret that argocd-server reads via the
# $<secret>:<key> reference syntax. VSO is declared in vso.tf; the VSO auth
# SA + VaultStaticSecret live in argocd-vso.tf.

resource "vault_policy" "argocd" {
  name = "argocd"

  policy = <<-EOT
    path "secret/data/argocd/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/argocd/*" {
      capabilities = ["read", "list"]
    }
  EOT
}

resource "vault_kubernetes_auth_backend_role" "argocd" {
  backend                          = "kubernetes"
  role_name                        = "argocd"
  bound_service_account_names      = ["argocd-vso"]
  bound_service_account_namespaces = ["argocd"]
  token_ttl                        = 3600
  token_max_ttl                    = 86400
  token_policies                   = [vault_policy.argocd.name]
}

resource "vault_kv_secret_v2" "argocd_oidc" {
  mount = "secret"
  name  = "argocd/oidc"

  data_json = jsonencode({
    client_secret = random_password.keycloak_argocd_client_secret.result
  })
}
