# Vault declarative config (policies, auth roles, seed secrets).
#
# Bring-up order on a fresh cluster:
#   1. terraform apply -target=helm_release.vault \
#                       -target=aws_eks_pod_identity_association.vault
#   2. kubectl -n vault exec -it vault-0 -- vault operator init \
#        -recovery-shares=5 -recovery-threshold=3
#      -> save root + recovery keys to 1Password
#   3. ./vault-approle-bootstrap.sh  (uses root token to create the AppRole
#      for terraform; prints role_id + secret_id)
#   4. export TF_VAR_vault_terraform_role_id=...
#      export TF_VAR_vault_terraform_secret_id=...
#   5. terraform apply  (applies this file + everything else)

# =============================================================================
# Pilot: rag-service consumes a demo secret via Vault Agent Injector sidecar
# =============================================================================

resource "vault_policy" "rag_service" {
  name = "rag-service"

  policy = <<-EOT
    # Read-only on secrets under secret/rag-service/*
    path "secret/data/rag-service/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/rag-service/*" {
      capabilities = ["read", "list"]
    }
    # Dynamic Postgres credentials — Vault's database engine issues a
    # fresh username/password per call, auto-revokes at TTL.
    path "database/creds/rag-service-db" {
      capabilities = ["read"]
    }
  EOT
}

resource "vault_kubernetes_auth_backend_role" "rag_service" {
  backend                          = "kubernetes"
  role_name                        = "rag-service"
  bound_service_account_names      = ["rag-service"]
  bound_service_account_namespaces = ["rag"]
  token_ttl                        = 3600
  token_max_ttl                    = 86400
  token_policies                   = [vault_policy.rag_service.name]
}

# Demo secret so we can prove sidecar injection works end-to-end. Gets
# rendered into /vault/secrets/demo inside the rag-service container when
# the pod is annotated with the vault.hashicorp.com/agent-inject-* keys.
resource "vault_kv_secret_v2" "rag_service_demo" {
  mount = "secret"
  name  = "rag-service/demo"

  data_json = jsonencode({
    hello         = "from vault"
    rotation_note = "this value comes from Vault via agent injector sidecar"
  })
}

# =============================================================================
# Grafana: admin password + Keycloak OIDC client secret via sidecar injection
# =============================================================================
# SA is created by the kube-prometheus-stack grafana subchart, named
# <release>-grafana = kube-prometheus-stack-grafana.

resource "vault_policy" "grafana" {
  name = "grafana"

  policy = <<-EOT
    path "secret/data/grafana/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/grafana/*" {
      capabilities = ["read", "list"]
    }
  EOT
}

resource "vault_kubernetes_auth_backend_role" "grafana" {
  backend                          = "kubernetes"
  role_name                        = "grafana"
  bound_service_account_names      = ["kube-prometheus-stack-grafana"]
  bound_service_account_namespaces = ["monitoring"]
  token_ttl                        = 3600
  token_max_ttl                    = 86400
  token_policies                   = [vault_policy.grafana.name]
}

# Grafana admin password sourced from tfvars; Vault is the runtime delivery
# path. Rotating in tfvars + applying re-writes Vault, and the next pod
# restart picks it up via the sidecar (but note: admin password lives in
# Grafana's SQLite after first boot, so rotation needs a UI/API change too).
resource "vault_kv_secret_v2" "grafana_admin" {
  mount = "secret"
  name  = "grafana/admin"

  data_json = jsonencode({
    password = var.grafana_admin_password
  })
}

# Keycloak OIDC client secret for Grafana, generated by random_password in
# keycloak-realm.tf and also baked into the realm JSON (Keycloak's side of
# the pair). Here we deliver it to Grafana via sidecar instead of a k8s
# Secret + envValueFrom.
resource "vault_kv_secret_v2" "grafana_oidc" {
  mount = "secret"
  name  = "grafana/oidc"

  data_json = jsonencode({
    client_secret = random_password.keycloak_grafana_client_secret.result
  })
}

# =============================================================================
# ArgoCD: Keycloak OIDC client secret via Vault Secrets Operator (VSO)
# =============================================================================
# ArgoCD's oidc.config requires a k8s Secret (no file/env fallback), so VSO
# syncs this Vault path into a k8s Secret that argocd-server reads via the
# $<secret>:<key> reference syntax. VSO is declared in vso.tf; the VSO auth
# SA + VaultStaticSecret live in argocd-vso.tf.

resource "vault_policy" "argocd" {
  name = "argocd"

  policy = <<-EOT
    path "secret/data/argocd/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/argocd/*" {
      capabilities = ["read", "list"]
    }
  EOT
}

resource "vault_kubernetes_auth_backend_role" "argocd" {
  backend                          = "kubernetes"
  role_name                        = "argocd"
  bound_service_account_names      = ["argocd-vso"]
  bound_service_account_namespaces = ["argocd"]
  token_ttl                        = 3600
  token_max_ttl                    = 86400
  token_policies                   = [vault_policy.argocd.name]
}

resource "vault_kv_secret_v2" "argocd_oidc" {
  mount = "secret"
  name  = "argocd/oidc"

  data_json = jsonencode({
    client_secret = random_password.keycloak_argocd_client_secret.result
  })
}

# =============================================================================
# Keycloak DB password — shared by keycloak-0 and keycloak-postgres-postgresql-0
# =============================================================================
# Both pods must agree on the same value or Keycloak can't auth to Postgres.
# Delivery via VSO → single k8s Secret read by both charts through their
# existingSecret values (see keycloak.tf). Two key names written to the same
# value so Bitnami's postgresql chart (password / postgres-password) is happy
# out of the box; Keycloak chart's key is overridden to `password` in its
# existingSecretPasswordKey.

resource "vault_policy" "keycloak_db" {
  name = "keycloak-db"

  policy = <<-EOT
    path "secret/data/keycloak/*" {
      capabilities = ["read"]
    }
    path "secret/metadata/keycloak/*" {
      capabilities = ["read", "list"]
    }
  EOT
}

resource "vault_kubernetes_auth_backend_role" "keycloak_db" {
  backend                          = "kubernetes"
  role_name                        = "keycloak-db"
  bound_service_account_names      = ["keycloak-vso"]
  bound_service_account_namespaces = ["keycloak"]
  token_ttl                        = 3600
  token_max_ttl                    = 86400
  token_policies                   = [vault_policy.keycloak_db.name]
}

# Separate role for the Keycloak pod itself — uses Agent Injector sidecar
# to pull its DB password as a file. Keycloak 26 supports a `file:` prefix
# on any config value, so KC_DB_PASSWORD=file:/vault/secrets/db-password
# reads from the injected file. Two delivery mechanisms for the same
# credential: VSO for Postgres (native k8s Secret via Bitnami chart's
# auth.existingSecret), Agent Injector for Keycloak (file via Quarkus
# config-source).
resource "vault_kubernetes_auth_backend_role" "keycloak_pod" {
  backend                          = "kubernetes"
  role_name                        = "keycloak"
  bound_service_account_names      = ["keycloak"]
  bound_service_account_namespaces = ["keycloak"]
  token_ttl                        = 3600
  token_max_ttl                    = 86400
  token_policies                   = [vault_policy.keycloak_db.name]
}

resource "vault_kv_secret_v2" "keycloak_db" {
  mount = "secret"
  name  = "keycloak/db"

  data_json = jsonencode({
    password            = var.keycloak_db_password
    "postgres-password" = var.keycloak_db_password
  })
}

# Keycloak master admin password. Bitnami chart's auth.existingSecret reads
# key "admin-password" by default. Same keycloak-db policy + vault auth role
# covers this path since both are under secret/keycloak/*.
resource "vault_kv_secret_v2" "keycloak_admin" {
  mount = "secret"
  name  = "keycloak/admin"

  data_json = jsonencode({
    "admin-password" = var.keycloak_admin_password
  })
}

# =============================================================================
# Dynamic Postgres credentials for rag-service via RDS Aurora (rds.tf)
# =============================================================================
# Vault's database secrets engine connects to Aurora with the master creds,
# and issues short-lived per-role users on demand. Each pod-driven call to
# /database/creds/rag-service-db creates a fresh Postgres user with 1h TTL.
# Vault revokes at expiry; no stale creds accumulate in the DB.

resource "vault_mount" "database" {
  path        = "database"
  type        = "database"
  description = "Dynamic credentials issuer for RDS Aurora Postgres"
}

resource "vault_database_secret_backend_connection" "rds_postgres" {
  backend       = vault_mount.database.path
  name          = "rds-postgres"
  allowed_roles = ["rag-service-db"]

  postgresql {
    connection_url = "postgresql://{{username}}:{{password}}@${aws_db_instance.rag.address}:5432/ragdb?sslmode=require"
    username       = aws_db_instance.rag.username
    password       = random_password.rds_master.result
    # Rotate the master password used by Vault on boot / refresh. Keeps the
    # long-lived admin password out of any caller's hands after initial
    # registration. If you ever need to disable this for debugging, set
    # password_policy or switch to static creds.
    # (Note: rotate_root would be nice here but runs once and is irreversible;
    # for a lab we skip it so destroy/apply cycles don't strand us.)
  }
}

resource "vault_database_secret_backend_role" "rag_service_db" {
  backend = vault_mount.database.path
  name    = "rag-service-db"
  db_name = vault_database_secret_backend_connection.rds_postgres.name

  default_ttl = 3600   # 1 hour — pod sees rotation every hour
  max_ttl     = 86400  # 24h hard cap

  # Create a role with CRUD on whatever's in public schema. Expand to specific
  # tables / schemas once rag-service has its own DB layout.
  creation_statements = [
    "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';",
    "GRANT USAGE ON SCHEMA public TO \"{{name}}\";",
    "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO \"{{name}}\";",
    "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO \"{{name}}\";",
  ]

  # Graceful teardown on TTL expiry.
  revocation_statements = [
    "REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM \"{{name}}\";",
    "REVOKE ALL PRIVILEGES ON SCHEMA public FROM \"{{name}}\";",
    "REVOKE ALL PRIVILEGES ON DATABASE ragdb FROM \"{{name}}\";",
    "DROP ROLE IF EXISTS \"{{name}}\";",
  ]
}
